// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// cdm_kli_id_C
Rcpp::List cdm_kli_id_C(Rcpp::NumericMatrix pjk, Rcpp::NumericMatrix sc);
RcppExport SEXP CDM_cdm_kli_id_C(SEXP pjkSEXP, SEXP scSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type pjk(pjkSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type sc(scSEXP);
    rcpp_result_gen = Rcpp::wrap(cdm_kli_id_C(pjk, sc));
    return rcpp_result_gen;
END_RCPP
}
// din_deterministic_devcrit_C
Rcpp::List din_deterministic_devcrit_C(Rcpp::NumericMatrix DAT, Rcpp::NumericMatrix DATRESP, Rcpp::NumericMatrix LATRESP, Rcpp::NumericVector GUESS, Rcpp::NumericVector SLIP);
RcppExport SEXP CDM_din_deterministic_devcrit_C(SEXP DATSEXP, SEXP DATRESPSEXP, SEXP LATRESPSEXP, SEXP GUESSSEXP, SEXP SLIPSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type DAT(DATSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type DATRESP(DATRESPSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type LATRESP(LATRESPSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type GUESS(GUESSSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type SLIP(SLIPSEXP);
    rcpp_result_gen = Rcpp::wrap(din_deterministic_devcrit_C(DAT, DATRESP, LATRESP, GUESS, SLIP));
    return rcpp_result_gen;
END_RCPP
}
// din_jml_devcrit_C
Rcpp::List din_jml_devcrit_C(Rcpp::NumericMatrix DAT, Rcpp::NumericMatrix DATRESP, Rcpp::NumericMatrix LATRESP, Rcpp::NumericVector GUESS, Rcpp::NumericVector SLIP);
RcppExport SEXP CDM_din_jml_devcrit_C(SEXP DATSEXP, SEXP DATRESPSEXP, SEXP LATRESPSEXP, SEXP GUESSSEXP, SEXP SLIPSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type DAT(DATSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type DATRESP(DATRESPSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type LATRESP(LATRESPSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type GUESS(GUESSSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type SLIP(SLIPSEXP);
    rcpp_result_gen = Rcpp::wrap(din_jml_devcrit_C(DAT, DATRESP, LATRESP, GUESS, SLIP));
    return rcpp_result_gen;
END_RCPP
}
// generalized_distance_method__C
Rcpp::List generalized_distance_method__C(Rcpp::NumericMatrix data, Rcpp::NumericMatrix dataresp, Rcpp::NumericMatrix idealresp, Rcpp::NumericVector theta, Rcpp::NumericVector a, Rcpp::NumericVector b);
RcppExport SEXP CDM_generalized_distance_method__C(SEXP dataSEXP, SEXP datarespSEXP, SEXP idealrespSEXP, SEXP thetaSEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type dataresp(datarespSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type idealresp(idealrespSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(generalized_distance_method__C(data, dataresp, idealresp, theta, a, b));
    return rcpp_result_gen;
END_RCPP
}
// ideal_resp_pattern__C
Rcpp::NumericMatrix ideal_resp_pattern__C(Rcpp::NumericMatrix qmatrix, Rcpp::NumericMatrix skillspace);
RcppExport SEXP CDM_ideal_resp_pattern__C(SEXP qmatrixSEXP, SEXP skillspaceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type qmatrix(qmatrixSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type skillspace(skillspaceSEXP);
    rcpp_result_gen = Rcpp::wrap(ideal_resp_pattern__C(qmatrix, skillspace));
    return rcpp_result_gen;
END_RCPP
}
// IRT_predict
Rcpp::List IRT_predict(Rcpp::NumericMatrix resp, Rcpp::NumericVector irf1, int K, int TP);
RcppExport SEXP CDM_IRT_predict(SEXP respSEXP, SEXP irf1SEXP, SEXP KSEXP, SEXP TPSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type resp(respSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type irf1(irf1SEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type TP(TPSEXP);
    rcpp_result_gen = Rcpp::wrap(IRT_predict(resp, irf1, K, TP));
    return rcpp_result_gen;
END_RCPP
}
// calc_scoredistribution_cdm
Rcpp::NumericMatrix calc_scoredistribution_cdm(Rcpp::NumericMatrix P1, Rcpp::NumericMatrix Q1);
RcppExport SEXP CDM_calc_scoredistribution_cdm(SEXP P1SEXP, SEXP Q1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type P1(P1SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Q1(Q1SEXP);
    rcpp_result_gen = Rcpp::wrap(calc_scoredistribution_cdm(P1, Q1));
    return rcpp_result_gen;
END_RCPP
}
// modelfit_cor2_Cpp
Rcpp::List modelfit_cor2_Cpp(Rcpp::NumericMatrix posterior, Rcpp::NumericMatrix data, Rcpp::NumericMatrix dataresp, Rcpp::NumericMatrix probs1, Rcpp::NumericMatrix probs0, Rcpp::NumericMatrix ip, Rcpp::NumericMatrix expiijj);
RcppExport SEXP CDM_modelfit_cor2_Cpp(SEXP posteriorSEXP, SEXP dataSEXP, SEXP datarespSEXP, SEXP probs1SEXP, SEXP probs0SEXP, SEXP ipSEXP, SEXP expiijjSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type posterior(posteriorSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type dataresp(datarespSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type probs1(probs1SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type probs0(probs0SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type ip(ipSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type expiijj(expiijjSEXP);
    rcpp_result_gen = Rcpp::wrap(modelfit_cor2_Cpp(posterior, data, dataresp, probs1, probs0, ip, expiijj));
    return rcpp_result_gen;
END_RCPP
}
// probs_pcm_groups_C
Rcpp::List probs_pcm_groups_C(Rcpp::NumericMatrix dat, Rcpp::NumericMatrix dat_resp, Rcpp::NumericVector group, Rcpp::NumericMatrix probs, int CC, int TP);
RcppExport SEXP CDM_probs_pcm_groups_C(SEXP datSEXP, SEXP dat_respSEXP, SEXP groupSEXP, SEXP probsSEXP, SEXP CCSEXP, SEXP TPSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type dat(datSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type dat_resp(dat_respSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type group(groupSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type probs(probsSEXP);
    Rcpp::traits::input_parameter< int >::type CC(CCSEXP);
    Rcpp::traits::input_parameter< int >::type TP(TPSEXP);
    rcpp_result_gen = Rcpp::wrap(probs_pcm_groups_C(dat, dat_resp, group, probs, CC, TP));
    return rcpp_result_gen;
END_RCPP
}
// calccounts_pcm_groups_C
Rcpp::List calccounts_pcm_groups_C(Rcpp::NumericMatrix dat, Rcpp::NumericMatrix dat_resp, Rcpp::NumericVector group, Rcpp::NumericMatrix fyiqk, Rcpp::NumericMatrix pik, int CC, Rcpp::NumericVector weights);
RcppExport SEXP CDM_calccounts_pcm_groups_C(SEXP datSEXP, SEXP dat_respSEXP, SEXP groupSEXP, SEXP fyiqkSEXP, SEXP pikSEXP, SEXP CCSEXP, SEXP weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type dat(datSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type dat_resp(dat_respSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type group(groupSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type fyiqk(fyiqkSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type pik(pikSEXP);
    Rcpp::traits::input_parameter< int >::type CC(CCSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type weights(weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(calccounts_pcm_groups_C(dat, dat_resp, group, fyiqk, pik, CC, weights));
    return rcpp_result_gen;
END_RCPP
}
// calc_slca_probs
Rcpp::NumericVector calc_slca_probs(Rcpp::NumericMatrix XdesM, Rcpp::NumericVector dimXdes, Rcpp::NumericVector Xlambda);
RcppExport SEXP CDM_calc_slca_probs(SEXP XdesMSEXP, SEXP dimXdesSEXP, SEXP XlambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type XdesM(XdesMSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type dimXdes(dimXdesSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Xlambda(XlambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_slca_probs(XdesM, dimXdes, Xlambda));
    return rcpp_result_gen;
END_RCPP
}
// calc_slca_deriv
Rcpp::List calc_slca_deriv(Rcpp::NumericMatrix XdesM, Rcpp::NumericVector dimXdes, Rcpp::NumericVector Xlambda, Rcpp::NumericVector probs, Rcpp::NumericVector nik, Rcpp::NumericVector Nik);
RcppExport SEXP CDM_calc_slca_deriv(SEXP XdesMSEXP, SEXP dimXdesSEXP, SEXP XlambdaSEXP, SEXP probsSEXP, SEXP nikSEXP, SEXP NikSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type XdesM(XdesMSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type dimXdes(dimXdesSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Xlambda(XlambdaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type probs(probsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type nik(nikSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Nik(NikSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_slca_deriv(XdesM, dimXdes, Xlambda, probs, nik, Nik));
    return rcpp_result_gen;
END_RCPP
}
// calc_Xdes
Rcpp::List calc_Xdes(Rcpp::NumericVector XDES, Rcpp::NumericVector dimXdes);
RcppExport SEXP CDM_calc_Xdes(SEXP XDESSEXP, SEXP dimXdesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type XDES(XDESSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type dimXdes(dimXdesSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_Xdes(XDES, dimXdes));
    return rcpp_result_gen;
END_RCPP
}

