## File Name: RcppExports.R
## File Version: 0.02
## File Last Change: 2017-06-23 13:36:04
# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cdm_kli_id_C <- function(pjk, sc) {
    .Call('CDM_cdm_kli_id_C', PACKAGE = 'CDM', pjk, sc)
}

din_deterministic_devcrit_C <- function(DAT, DATRESP, LATRESP, GUESS, SLIP) {
    .Call('CDM_din_deterministic_devcrit_C', PACKAGE = 'CDM', DAT, DATRESP, LATRESP, GUESS, SLIP)
}

din_jml_devcrit_C <- function(DAT, DATRESP, LATRESP, GUESS, SLIP) {
    .Call('CDM_din_jml_devcrit_C', PACKAGE = 'CDM', DAT, DATRESP, LATRESP, GUESS, SLIP)
}

generalized_distance_method__C <- function(data, dataresp, idealresp, theta, a, b) {
    .Call('CDM_generalized_distance_method__C', PACKAGE = 'CDM', data, dataresp, idealresp, theta, a, b)
}

ideal_resp_pattern__C <- function(qmatrix, skillspace) {
    .Call('CDM_ideal_resp_pattern__C', PACKAGE = 'CDM', qmatrix, skillspace)
}

IRT_predict <- function(resp, irf1, K, TP) {
    .Call('CDM_IRT_predict', PACKAGE = 'CDM', resp, irf1, K, TP)
}

calc_scoredistribution_cdm <- function(P1, Q1) {
    .Call('CDM_calc_scoredistribution_cdm', PACKAGE = 'CDM', P1, Q1)
}

modelfit_cor2_Cpp <- function(posterior, data, dataresp, probs1, probs0, ip, expiijj) {
    .Call('CDM_modelfit_cor2_Cpp', PACKAGE = 'CDM', posterior, data, dataresp, probs1, probs0, ip, expiijj)
}

probs_pcm_groups_C <- function(dat, dat_resp, group, probs, CC, TP) {
    .Call('CDM_probs_pcm_groups_C', PACKAGE = 'CDM', dat, dat_resp, group, probs, CC, TP)
}

calccounts_pcm_groups_C <- function(dat, dat_resp, group, fyiqk, pik, CC, weights) {
    .Call('CDM_calccounts_pcm_groups_C', PACKAGE = 'CDM', dat, dat_resp, group, fyiqk, pik, CC, weights)
}

calc_slca_probs <- function(XdesM, dimXdes, Xlambda) {
    .Call('CDM_calc_slca_probs', PACKAGE = 'CDM', XdesM, dimXdes, Xlambda)
}

calc_slca_deriv <- function(XdesM, dimXdes, Xlambda, probs, nik, Nik) {
    .Call('CDM_calc_slca_deriv', PACKAGE = 'CDM', XdesM, dimXdes, Xlambda, probs, nik, Nik)
}

calc_Xdes <- function(XDES, dimXdes) {
    .Call('CDM_calc_Xdes', PACKAGE = 'CDM', XDES, dimXdes)
}

